import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers/Providers";
import { Toaster } from "sonner";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BabyFood",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>

        <html lang="en" data-theme='light' >
          <body className={inter.className}>
            <>
              <Toaster position="top-right" />
              {children}
            </>
          </body>
        </html>

    </Providers>
  );
}
